Use KainosJob_PatrykK;

create table User(
    user_id smallint primary key auto_increment,
    email varchar(50) not null unique,
    `password` varchar(20) not null,
    `role` enum('Employee', 'Admin') not null,
    token varchar(200) UNIQUE not null,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    phone_number varchar(15) not null,
    `location` enum('Belfast', 'Gdansk', 'Birmingham', 'London')
);

create table Capability(
    cap_id smallint primary key auto_increment,
    cap_name varchar(50) not null
);

create table Job_Roles(
    role_id smallint primary key auto_increment,
    role_name varchar(50) not null,
    role_description varchar(1000) not null,
    sharepoint_url varchar(1000) not null,
    cap_id smallint,
    foreign key (cap_id) references Capability(cap_id) 
);


insert into 
Capability (cap_name) 
values 
('Engineering'),
('Platforms'),
('Data'),
('Artificial Intelligence'),
('Cyber Seurity'), 
('Workday'),
('Experience Design'),
('Product'),
('Delivery'),
('Operations'),
('Business Development and Marketing'),
('Organisational Strategy and Planning'),
('People'),
('Commercial and Financial Management'),
('Business Services Support');


insert into 
Job_Roles (role_name, role_description, sharepoint_url, cap_id)
values
('Innovation Lead',
 'As an Innovation Lead (Consultant) in Kainos, youll be responsible will lead the team, working with the Innovation Lead in a dynamic and hands-on role which will involve managing and developing the team, implementing and shaping Kainos innovation strategy and effectively communicating the exciting work we undertake both internally and within the wider technology community.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Innovation%20Lead%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1',
  1),
('Lead Software Engineer',
 'As a Lead Software Engineer (Consultant) in Kainos, you’ll be responsible for leading teams and developing high quality solutions which delight our customers and impact the lives of users worldwide. It’s a fast-paced environment so it is important for you to make sound, reasoned decisions. You’ll do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Lead%20Software%20Engineer%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1',
  1),
('Lead NFTEngineer',
 'As a Lead NFTEngineer(Consultant)in Kainos, youll be a technical leader and innovator in Non-Functional Testing, providing strong test leadership and direction within a multi-skilled agile team. Taking responsibility for the strategy, design and development of non-functional requirements & tests, youll help the team to deliver working application software that is scalable and performant for theusers. Its a fast-paced environment so it is important for you to make sound, reasoned decisions.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Lead%20NFT%20Engineer%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1',
  1),
('Technical Architect',
 'As a Technical Architect (Consultant) in Kainos, you’ll be responsible for leading teams and developing high quality solutions which delight our customers and impact the lives of users worldwide. As a technical leader on a project, you’ll work with customer architects to agree technical designs, advising on estimated effort and technical implications of user stories and user journeys.',
  'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspid=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Technical%20Architect%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1',
   1),
('Senior People Support Associate',
 'As a Senior People Support Associate at Kainos, you will provide an excellent service across all Business Units in Kainos globally. You will be responsible for offering advice and guidance to employees on all People related matters, ensuring legislative guidance is adhered to and high standards are met and maintained in all people related processes. You will also be a key player in supporting the delivery of the People Strategy.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FPeople%2FPeople%20Support%2FJob%20profile%20%2D%20Senior%20People%20Support%20Associate%20%28Senior%20Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FPeople%2FPeople%20Support&p=true&ga=1',
 13),
('Talent Acquisition Specialist',
 'The Talent Acquisition team at Kainos are responsible for end to end delivery aligned to BU hiring demands. Based in locations across UK &I, Europe and North America, the team focus on direct sourcing channels to create a best in class candidate experience, in the most cost-effective way',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FPeople%2FTalent%20Acquisition%2FJob%20profile%20%2D%20Talent%20Acquisition%20Specialist%20%28As%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FPeople%2FTalent%20Acquisition&p=true&ga=1',
  13),
('Service Delivery Manager',
 'As a Service Delivery Manager in Kainos, you will assist in the direction and management of Support. Manages and champions assigned areas of ownership across assigned clients and within Kainos as a whole. Responsible for managing the delivery of a support service, and managing the client-relationship, across projects. Works with Clients and the Sales team to drive out new opportunities and expand Kainos footprint within our account.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FDelivery%2FJob%20profile%20%2D%20Service%20Delivery%20Management%20%28Manager%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FDelivery&p=true&ga=1',
  9),

('Workday Integrations Consultant',
 'As a Workday Integrations Consultant (Trainee) in Kainos, you will be responsible for supporting the successful specification, design and configuration of enterprise-scale Workday product solutions. This will be done by working with internal delivery teams to provide solutions that are fit for purpose and commercially viable. Understanding and translating customer requirements, as well as hands-on product configuration is essential for this role.',
 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FWorkday%2FIntegrations%2FJob%20Profile%20%2D%20Integrations%20Consultant%20%28Trainee%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FWorkday%2FIntegrations&p=true&ga=1',
 6);

INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id)
   VALUES ('Data Engineer', 
   'As a Data Engineer (Associate) in Kainos you will work within a multi-skilled agile team to design and develop large-scale data processing software to meet user needs in demanding production environments.  ', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Data%20Engineer%20%28As%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Trainee Data Engineer', 
   'As a Trainee Data Engineer (Trainee) in Kainos you will enter the Kainos Big Data Academy. Successful graduates of the Big Data Academy will become Associate Data Engineers, following a period of extended project-based training.  ', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Trainee%20Data%20Engineer%20%28T%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Data Analyst', 
   'As a Data Analyst (Associate) in Kainos, you’ll be responsible for matching the needs of data insight with understanding of the available data. Data analysts work closely with customers to produce insight products including reports, dashboards and visualisations but also contribute to project understanding of existing data structures so that inputs and outputs are fully understood.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Data%20Analyst%20%28As%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Senior Data Engineer', 
   'As a Senior Data Engineer (Senior Associate) at Kainos, you will be responsible or designing and developing data processing and data persistence software components for solutions which handle data at scale. Working in agile teams, Senior Data Engineers provide strong development leadership and take responsibility for significant technical components of data systems . You will work within a multi-skilled agile team to design and develop large-scale data processing software to meet user needs in demanding production environments.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Senior%20Data%20Engineer%20%28SA%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Senior Data Analyst', 
   'As a Senior Data Analyst (Senior Associate) at Kainos, you’ll be responsible for matching the needs of data insight with understanding of the available data. Data analysts work closely with customers to produce insight products including reports, dashboards and visualisations but also contribute to project understanding of existing data structures so that inputs and outputs are fully understood. It therefore has a strong consulting element.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Senior%20Data%20Analyst%20%28SA%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Principal Data Solution Architect', 
   'As a Principal Data Solution Architect in Kainos, you’ll be accountable for successful delivery of contemporary data solutions across multiple customers.  You’ll have gravitas within the data community and strong thought leadership, working with senior stakeholders to agree principles, strategic direction and functional and non-functional designs. You will manage other architects and engineers in the capability to help them navigate their careers.  ', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Principal%20Data%20Solution%20Architect%20%28P%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Principal Data Architect', 
   'As a Principal Data Architect in Kainos, you’ll be accountable for successful delivery of data solutions across multiple customers; taking responsibility across traditional data architecture disciplines around data structures, data flows, data sourcing and data governance.  This will mean working at a solution and enterprise level.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Principal%20Data%20Architect%20%28P%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Data Solution Architect', 
   'As a Data Solution Architect (Manager) in Kainos, you’ll be responsible for a multi- skilled agile teams to design and deliver contemporary data solutions. You will be a quality orientated pragmatist, where you balance trade-offs to successfully deliver complex solutions. You will be viewed as an authority figure for data technology solutions, providing strong technical and thought leadership.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Data%20Solution%20Architect%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Data Architect', 
   'As a Data Architect (Manager) in Kainos, you’ll be responsible for providing SME guidance in traditional data architecture disciplines around data structures, data flows, data sourcing and data governance. Data Architects work closely with clients to understand their data requirements and take responsibility for ensuring solutions are fit for purpose. They also provide technical leadership for the rest of the team in the area of data.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Data%20Architect%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Data Consultant', 
   'As a Data Consultant(Manager) in Kainos, you will combinethought leadership, delivery and commercial experience to identify, securenew business aswe help customers on their digital transformation journeys which have vital data considerationswhere value can be unlocked.', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20Profile%20%2D%20Data%20Consultant%20%28M%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3),
   ('Lead Data Analyst', 
   'As a Lead Data Analyst(Consultant)in Kainos, you’ll workwithin a multi-skilled agile team to collect and analyse data and enable insight tosenior customers that drives business improvement.', 
   'https://kainossoftwareltd.sharepoint.com/sites/PeopleTeam-SharedDrive/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPeopleTeam%2DSharedDrive%2FShared%20Documents%2FPeople%20Team%20Shared%20Drive%2FOrganisational%20Development%20%26%20Learning%2FCareer%20Lattice%2FApproved%20Job%20Profiles%2FData%2FJob%20profile%20%2D%20Lead%20Data%20Analyst%20%28C%29%2Epdf&parent=%2Fsites%2FPeopleTeam%2DSharedDrive%2FShared%20Documents%2FPeople%20Team%20Shared%20Drive%2FOrganisational%20Development%20%26%20Learning%2FCareer%20Lattice%2FApproved%20Job%20Profiles%2FData&p=true&ga=1', 
   3),
   ('Data Technical Architect', 
   'As a Data Technical Architect (Consultant) in Kainos, you will be responsible for designing and delivering technical components as part of a larger data solution. You will work closely with Solution Architects and Customer Architects to integrate these components into quality data solutions', 
   'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FData%2FJob%20profile%20%2D%20Data%20Technical%20Architect%20%28C%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FData&p=true&ga=1', 
   3);

   #AI capability - 4
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Trainee AI Engineer', 'As a Trainee Artificial Intelligence (AI) Engineer in Kainos, you’ll be responsible for contributing to the development of high-quality solutions which integrate AI and ML technologies that delight our customers and impact the lives of users worldwide. You’ll do this whilst gaining awareness and learning about new AI technologies, frameworks and approaches, with talented colleagues that will help you to learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20Trainee%20AI%20Engineer%20%28Trainee%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Associate Data Scientist', 'As  an  Associate  Data  Scientist  in  Kainos,  you’ll  be  responsible  for  developing  high  quality  solutions that use AI and ML technologies to delight our customers and impact the lives of users  worldwide.  It’s  a  fast-paced  environment  so  it  is  important  for  you  to  make  sound,  reasoned decisions. You’ll do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20Associate%20Data%20Scientist%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Senior AI Engineer', 'As a   Senior Artificial Intelligence (AI) Engineer in Kainos, you’ll be responsible for developing high  quality  solutions  that  use  AI  and  ML  technologies  which  delight  our  customers  and  impact the lives of users worldwide. It’s a fast-paced environment so it is important for you to make sound, reasoned decisions. You’ll do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow as you, in turn, mentor those around you.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20Senior%20AI%20Engineer%20%28Senior%20Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Consultant Data Scientist', 'As a Consultant Data Scientist in Kainos, you’ll be responsible for leading teams and developing high quality solutions that use AI and ML technologies to delight our customers and impact the lives of users worldwide. It’s a fast-paced environment so it is important for you to make sound, reasoned decisions. You’ll do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow. As the technical leader in the team, you will also interact with customers, share knowledge and mentor those around you.You will manage, coach and develop a small number of staff, with a focus on managing employee performance and assisting in their career development. You’ll also provide direction and leadership for your team as you solve challenging problems together.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20Consultant%20Data%20Scientist%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('AI Engineering Manager', 'As an Artificial Intelligence (AI) Engineer Manager in Kainos, you’ll be responsible for successful delivery of large-scale high-quality solutions that use AI and ML technologiesthat delight our customers and impact the lives of users worldwide.  You will provide leadership and support to AI engineering teams by understanding the outcomes the solution is trying to achieve, the engineering implications and complexity surrounding you and your teams designs and helping teams make the right decisions.  You’ll work with senior stakeholders to agree architectural principles, strategic direction and functional and non-functional designs.  As a technical leader, you will work with your colleagues to inform development of policy and standards, develop customer relationships, account management and share knowledge and mentor those around you. You’ll do this whilst advising about new technologies and approaches to AI/ML, with room to learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20AI%20Engineering%20Manager%20%28Manager%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Principal Data Scientist', 'As a Principal Data Scientist in Kainos, you’ll be accountable for successful delivery of large-scale high-quality solutions that use AI and ML technologies that delight our customers and impact the lives of users worldwide.  You  will  provide  assurance  and  support  to  multi-skilled  agile  teams  by  understanding  the  outcomes   the   solution   is   trying   to   achieve,   the   data   implications   and   complexity   surrounding you and your teams designs and helping teams make the right decisions.  You’ll work with senior stakeholders to agree architectural principles, strategic direction and functional and non-functional designs. You will proactively develop new alliances with other vendors that will provide Kainos with new capability.  As  a  technical  leader,  you  will  work  with  your  colleagues  to  lead  development  of  policy  and  standards,  develop  customer  relationships,  develop  account  strategies  and  share  knowledge  and  mentor  those  around  you.  You’ll  do  this  whilst  advising  about  new  technologies and approaches to data, with room to learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence%2FJob%20Profile%20%2D%20Principal%20Data%20Scientist%20%28Principal%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FArtificial%20Intelligence&p=true&ga=1', 4);

#Operations capability - 10
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Programme Office Assistant', 'As a Programme Office Assistant(Trainee) at Kainos, you’ll be responsible for ensuring that a high-quality service is provided to the Project Management and Operations capabilities within the Digital Services/Workday/Central Servicesbusiness unit, demonstrating best practice throughout. You will provide administrative support for our engagements and will have a key role in the efficient management and delivery of these projects.You’ll work as part of the Digital Services/Workday/Central ServicesOperations PMO team and report into the Operations Manager. It’s a fast-paced environment so it is important for you to ensure that workload is prioritised, and tasks completed in a timely manner.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOperations%2FJob%20Profile%20%2D%20Programme%20Office%20Assistant%20%28T%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FOperations&p=true&ga=1', 10);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Staffing Consultant', 'As a Staffing Consultant (Senior Associate) at Kainos, you will be responsible for the day-to-day  staffing  of  projects  within  a  Business  unit.  You will ensure the  talent  pool  has  the  appropriate skills for forecasted projects while maximising profitable utilisation. You will also be responsible for ensuring the accurate closure of month end accounts.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOperations%2FJob%20Profile%20%2D%20Staffing%20Consultant%20%28Senior%20Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FOperations&p=true&ga=1', 10);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Operations Manager', 'As an Operations Manager (Manager) at Kainos, you will be responsible managing and improving the day to day operational processes within the Business Unit (BU) which supports  the management team and wider BU including sales, revenue and staff forecasting, staff allocation and recruitment forecasting, month-end closure, profitabilityand working capital.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOperations%2FJob%20Profile%20%2D%20Operations%20Manager%20%28Manager%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FOperations&p=true&ga=1', 10);

#Business Development and Marketing - 11
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Marketing Assistant', 'Our vision is to create a world-class business development and marketing capability for Kainos, fuelled by a diverse range of highly talented and motivated professionals working collaboratively and innovatively to ensure we continue our growth trajectory.We do this via an open and supportive environment where colleagues can share information, learn from one another, and excel in their own career.  With consistent ways of working aligned to industry best practice, we buildsustainable and predictable sales pipelines for our market-leading offerings.As a Marketing AssistantatKainos,we will support you to build your career in marketing. You will gain a solid grounding in many aspects ofmarketing, branding and communications.You will work as part of a team creatingand delivering the marketing campaignsand activitiesthatare aligned to commercial needsand designed to drive brand awareness/support recruitment/generate leads to fuel the sales pipeline.This will include competitor research, supporting content creationand aspects of activation, digital and social media marketing, reporting and evaluation, and undertaking defined projects to support delivery against plan.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FMarketing%20%2D%20Business%2FJob%20profile%20%2D%20Marketing%20Assistant%20%28T%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FMarketing%20%2D%20Business&p=true&ga=1', 11);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Customer Success Manager', 'Our vision is to create a world-class Customer Success capability for Kainos, fuelled by a diverse range of highly talented and motivated professionals working collaboratively and innovatively to ensure we retain clients and expand our footprint within existing clients to continue our growth trajectory.We do this via an open and supportive environment where colleagues can share information, learn from one another and excel in their own career.  With consistent ways of working aligned to industry best practice, we retain and grow our footprint by delivering on the clients desired outcomes for our market-leading offerings.As a Customer Success Manager (Consultant) at Kainos, you will partner with our customers post-sale to drive adoption and ensure customer satisfaction, growth, and retention. You will be the bridge between our Professional Services, Operational Support and Business Development teams. You will work directly with customers to ensure that their overall user experience with Kainos Smart is a success.We are looking for an individual who strike the right mix of sales, account management, domain knowledge and customer management skills.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FClient%20Management%2FJob%20Profile%20%2D%20Customer%20Success%20Manger%20%28Consultant%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FClient%20Management&p=true&ga=1', 11);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Digital Strategy Director', 'Our vision is to create a world-class business development and marketing capability for Kainos, fuelled by a diverse range of highly talented and motivated professionals working collaboratively and innovatively to ensure we continue our growth trajectory.We do this via an open and supportive environment where colleagues can share information, learn from one another, and excel in their own career.  With consistent ways of working aligned to industry best practice, we build sustainable and predictable sales pipelines for our market-leading offerings.As the Digital Strategy Director(Principal) atKainos, you willbe responsible globally the company’sdigital strategyand the tech stack(including ownership of our website platform), Marketo marketing automation (injecting great practice into our team to drive lead generation) and marketing operationsacross the world (ensuring marketing is transparent, consistent in approachand accountable viaROI reporting).You will use your extensive digital experience and commercial knowledge to lead and mentor themartech & Ops team whoact as a Digital Centre of Excellence tomarketing colleagues oncampaigns togenerate leads. You will foster strong relationships with key internal stakeholders and external partners acting as a trusted advisor.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FMarketing%20%2D%20Martech%20and%20Ops%2FJob%20profile%20%2D%20Digital%20Strategy%20Director%20%28P%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FBusiness%20Development%20and%20Marketing%2FMarketing%20%2D%20Martech%20and%20Ops&p=true&ga=1', 11);

#Organisational Strategy and Planning - 12
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('BU Chief Operating Officer', 'The Business Unit COOplays a strategic role in supportingthe deliveryof the business goals andstrategic ambitions–to be a great employer, to delight our customers and to be a growing, profitable and responsible company.  As an Executive in Kainos you will have an established track record in business planning, creating and operationalizing commercial and operational strategiesfor the business unit.As a member of the ExecutiveTeam,you will supportallour sustainability programmes and take personal responsibilityforone programme.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning%2FJob%20profile%20%2D%20BU%20COO%20%28Executive%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning&p=true&ga=1', 12);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Region/Sector Lead', 'As aRegion/Sector Lead (Leader) at Kainos,you will be accountable for sales, proposition development, customer relationships, overseeing project delivery and the Customer/Partnershiprelationship within the region/sector.This role sits within the Digital Services/WorkdayBUleadership team with accountability for sales performance, customer relationships, overseeing project delivery and Workday / sectorrelationship within a defined region. The Region/Sector Leadwill be responsible for leading sales and customer engagement teams to deliver the Sales Order Value and Customer Initiatives set out in the business plan. The Region/Sector Leadand their team will work closely with the BU Chief Operating Officer to accurately forecast demand, increase margin, develop propositions, and manage customer escalations.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning%2FJob%20profile%20-%20Region_Sector%20Lead%20%28Leader%29.pdf&parent=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning&p=true&ga=1', 12);
INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Head of Practice', 'As a Head of Practice (Manger) at Kainos, you will define and lead the strategy for the Practice. You will define the go to market offerings and commercial proposition for the Practice. You will also evolve the Practice to take advantage of Partner advancements and market changes. You will educate and motivate the sales Business Development function to deliver the SOV targets for the Practice. You will champion the growth of people and their capabilities to support the Practice in line with Kainos culture and values.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning%2FJob%20profile%20%2D%20Head%20of%20Practice%20%28Manager%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FOrganisational%20Strategy%20and%20Planning&p=true&ga=1', 12);

INSERT INTO Job_Roles( role_name, role_description,sharepoint_url,cap_id)
VALUES('Software Engineer','As a Software Engineer (Associate) in Kainos, you will be responsible for developing high quality solutions which delight our customers and impact the lives of users worldwide. You will do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow.','https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Software%20Engineer%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1', 1);

INSERT INTO Job_Roles( role_name, role_description,sharepoint_url,cap_id)
VALUES('Front-End Engineer','As a Front-end Engineer in Kainos, you will have the opportunity to use your expertise in developing high quality user interface solutions which delight our customers and impact the lives of users worldwide.   The projects you will join are varied, and often highly visible. You will be working in fast-paced, agile environments, so it is important for you to make sound, reasoned decisions, and recommendations on front-end and user interfaces with your colleagues. You are determined, flexible and always constructive; proactive in improving things and are always inclusive and respectful in your interactions with your team. You will be working alongside talented, diverse, enthusiastic colleagues, who will help you learn and develop as you, in turn, mentor those around you.', 'https://kainossoftwareltd.sharepoint.com/sites/PeopleTeam-SharedDrive/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FPeopleTeam%2DSharedDrive%2FShared%20Documents%2FPeople%20Team%20Shared%20Drive%2FOrganisational%20Development%20%26%20Learning%2FCareer%20Lattice%2FApproved%20Job%20Profiles%2FEngineering%2FEngineering%2FJob%20Profile%20%2D%20Senior%20Front%2DEnd%20Engineer%20%28SA%29%2Epdf&parent=%2Fsites%2FPeopleTeam%2DSharedDrive%2FShared%20Documents%2FPeople%20Team%20Shared%20Drive%2FOrganisational%20Development%20%26%20Learning%2FCareer%20Lattice%2FApproved%20Job%20Profiles%2FEngineering%2FEngineering&p=true&ga=1',1);

INSERT INTO Job_Roles( role_name, role_description,sharepoint_url,cap_id)
VALUES('Support Technician','As a Support Technician (Associate) in Kainos, you will be responsible for analysing and solving complicated technical issues.  You will adhere to ITIL standards and will participate fully in the Incident management lifecycle.   You will work closely with clients, internal teams and 3rd Party vendors to ensure that problems are resolved. You will do this whilst learning about new approaches, with talented colleagues that will help you to learn, develop and grow.','https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Support%20Technician%20%28As%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering',1);

INSERT INTO Job_Roles( role_name, role_description, sharepoint_url, cap_id)
VALUES('Test Engineer','As a Test Engineer (Associate) in Kainos, you will work within a multi-skilled agile team, developing and executing functional automated and manual tests to help the team deliver working application software that meets user needs. You will do this whilst learning about new technologies and approaches, with talented colleagues who will help you learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FTesting%2FJob%20profile%20%2D%20Test%20Engineer%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FTesting&p=true&ga=1', 1);

INSERT INTO Job_Roles( role_name, role_description, sharepoint_url, cap_id)
VALUES('Product Specialist','As a Product Specialist at Kainos you will be responsible for delivering high quality solutions which delight our customers and impact the lives of users worldwide. It is a fast paced environment so it is important for you to make sound, reasoned decisions. You will do this whilst learning about new technologies and approaches, with talented colleagues that will help you to learn, develop and grow.You will be responsible for capturing and mapping customer needs to product capabilities, supporting clients throughout their implementation lifecycle and business processes changes as well as providing information to relevant engineering teams on improvements or fixes required in the products.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20Profile%20%2D%20Product%20Specialist%20%28Associate%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1',1);

INSERT INTO Job_Roles( role_name, role_description, sharepoint_url, cap_id) 
VALUES('Trainee Software Engineer','As a Trainee Software Engineer with Kainos, you will work on projects where you can make a real difference to people’s lives – the lives of people you know. After taking part in our award-winning, seven-week Engineering Academy, you will then join one of our many project teams, to learn from our experienced developers, project managers and customer-facing staff. You’ll have great support and mentoring, balanced with the experience of being given real, meaningful work to do, to help you truly develop both technically and professionally.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Software%20Engineer%20%28Trainee%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1', 1);  

INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Trainee Test Engineer', 'As a Test Engineer (Trainee) in Kainos, you’ll work within a multi-skilled agile team, developing and executing functional automated and manual tests to help the team deliver working application software that meets user needs. You’ll do this whilst learning about new technologies and approaches, with talented colleagues who will help you learn, develop and grow.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FTesting%2FJob%20profile%20%2D%20Trainee%20Test%20Engineer%20%28Trainee%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FTesting&p=true&ga=1', 1);

INSERT INTO Job_Roles (role_name, role_description, sharepoint_url, cap_id) 
VALUES ('Apprentice Software Engineer', 'Our highly-regarded scheme gives the opportunity to work for us as an Apprentice Software Engineer four days per week, while studying for a part time degree in Computing Systems one day per week, with Ulster University, Jordanstown, completing your degree in just four and a half years.', 'https://kainossoftwareltd.sharepoint.com/people/Job%20Specifications/Forms/AllItems.aspx?id=%2Fpeople%2FJob%20Specifications%2FEngineering%2FJob%20profile%20%2D%20Apprentice%20Software%20Engineer%20%28Apprentice%29%2Epdf&parent=%2Fpeople%2FJob%20Specifications%2FEngineering&p=true&ga=1', 1);